# **Module `home_credit.tables`**

# **`HomeCreditTable.raw`**`()`

In [1]:
from home_credit.tables import CreditCardBalance

display(CreditCardBalance.raw())

load C:/Users/franc/Projects/pepper_credit_scoring_tool\dataset\pqt\credit_card_balance.pqt

RAW_CREDIT_CARD_BALANCE,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

# **`HomeCreditTable.cols_map`**`(group_name)`

In [2]:
from home_credit.tables import CreditCardBalance

display(CreditCardBalance.cols_map("balancing"))

{'AMT_BALANCE': ('BAL', '', 'AMT'),
 'AMT_DRAWINGS_CURRENT': ('DRW', 'TOT', 'AMT'),
 'AMT_RECEIVABLE_PRINCIPAL': ('RCV', '', 'AMT'),
 'AMT_TOTAL_RECEIVABLE': ('RCV', 'TOT', 'AMT'),
 'AMT_PAYMENT_CURRENT': ('PYT', '', 'AMT'),
 'AMT_PAYMENT_TOTAL_CURRENT': ('PYT', 'TOT', 'AMT')}

# **`HomeCreditTable.cols_group`**`(group_name, shorten)`

In [4]:
from home_credit.tables import CreditCardBalance

display(CreditCardBalance.cols_group("balancing"))
display(CreditCardBalance.cols_group("balancing", shorten=True))

['AMT_BALANCE',
 'AMT_DRAWINGS_CURRENT',
 'AMT_RECEIVABLE_PRINCIPAL',
 'AMT_TOTAL_RECEIVABLE',
 'AMT_PAYMENT_CURRENT',
 'AMT_PAYMENT_TOTAL_CURRENT']

[('BAL', '', 'AMT'),
 ('DRW', 'TOT', 'AMT'),
 ('RCV', '', 'AMT'),
 ('RCV', 'TOT', 'AMT'),
 ('PYT', '', 'AMT'),
 ('PYT', 'TOT', 'AMT')]

# **`HomeCreditTable.clean`**`()`

In [5]:
from home_credit.tables import CreditCardBalance

display(CreditCardBalance.clean())

load C:/Users/franc/Projects/pepper_credit_scoring_tool\dataset\pqt\credit_card_balance.pqt
load C:/Users/franc/Projects/pepper_credit_scoring_tool\dataset\pqt\application_train.pqt
load C:/Users/franc/Projects/pepper_credit_scoring_tool\dataset\pqt\application_test.pqt

RAW_CREDIT_CARD_BALANCE,TARGET,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,-1,2562384,378907,6,56.970,135000,0.0,877.5,0.0,877.5,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,1,2582071,363914,1,63975.555,45000,2250.0,2250.0,0.0,0.0,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,-1,1740877,371185,7,31815.225,450000,0.0,0.0,0.0,0.0,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,0,1389973,337855,4,236572.110,225000,2250.0,2250.0,0.0,0.0,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,0,1891521,126868,1,453919.455,450000,0.0,11547.0,0.0,11547.0,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,0,1036507,328243,9,0.000,45000,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0,0.0,0.0,0.0,Active,0,0
3840308,0,1714892,347207,9,0.000,45000,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,0,1302323,215757,9,275784.975,585000,270000.0,270000.0,0.0,0.0,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,0,1624872,430337,10,0.000,450000,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0,0.0,0.0,0.0,Active,0,0
3840311,0,2411345,236760,10,0.000,157500,0.0,0.0,0.0,0.0,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0