# **Extended `previous_application`**

# Load base clean data

1,670,214 clean entries.

In [1]:
from home_credit.tables import PreviousApplication
from home_credit.utils import display_frame_basic_infos
from pepper.univar import print_value_counts_dict

data = PreviousApplication.clean()
display_frame_basic_infos(data)
for col in PreviousApplication.cols_group("all_cats"):
    print_value_counts_dict(data, col)
display(data)
# ok data.info()

load C:/Users/franc/Projects/pepper_credit_scoring_tool\dataset\pqt\previous_application.pqt
Save to C:/Users/franc/Projects/pepper_credit_scoring_tool\tmp\persist\previous_application\clean\44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a.pqt
n_samples: 1 670 214
n_columns: 36, [('FLAG', 1), ('NFLAG', 2), ('NAME', 11), ('DAYS', 6), ('CNT', 1), ('AMT', 5), ('CHANNEL', 1), ('CODE', 1), ('HOUR', 1), ('PRODUCT', 1), ('RATE', 3), ('SELLERPLACE', 1), ('TARGET', 1), ('WEEKDAY', 1)]
NAME_CONTRACT_TYPE (4): {'Cash loans': 747553, 'Consumer loans': 729151, 'Revolving loans': 193164, 'XNA': 346}
NAME_CONTRACT_STATUS (4): {'Approved': 1036781, 'Canceled': 316319, 'Refused': 290678, 'Unused offer': 26436}
CODE_REJECT_REASON (9): {'XAP': 1353093, 'HC': 175231, 'LIMIT': 55680, 'SCO': 37467, 'CLIENT': 26436, 'SCOFR': 12811, 'XNA': 5244, 'VERIF': 3535, 'SYSTEM': 717}
NAME_CASH_LOAN_PURPOSE (25): {'XAP': 922661, 'XNA': 677918, 'Repairs': 23765, 'Other': 15608, 'Urgent needs': 8412, 'Buying a used car': 2888, 'Building a house or an annex': 2693, 'Everyday expenses': 2416, 'Medicine': 2174, 'Payments on other loans': 1931, 'Education': 1573, 'Journey': 1239, 'Purchase of electronic equipment': 1061, 'Buying a new car': 1012, 'Wedding / gift / holiday': 962, 'Buying a home': 865, 'Car repairs': 797, 'Furniture': 749, 'Buying a holiday home / land': 533, 'Business development': 426, 'Gasification / water supply': 300, 'Buying a garage': 136, 'Hobby': 55, 'Money for a third person': 25, 'Refusal to name the goal': 15}
NAME_TYPE_SUITE (8): {None: 820405, 'Unaccompanied': 508970, 'Family': 213263, 'Spouse, partner': 67069, 'Children': 31566, 'Other_B': 17624, 'Other_A': 9077, 'Group of people': 2240}
NAME_CLIENT_TYPE (4): {'Repeater': 1231261, 'New': 301363, 'Refreshed': 135649, 'XNA': 1941}
NAME_PAYMENT_TYPE (4): {'Cash through the bank': 1033552, 'XNA': 627384, 'Non-cash from your account': 8193, 'Cashless from the account of the employer': 1085}
NAME_GOODS_CATEGORY (28): {'XNA': 950809, 'Mobile': 224708, 'Consumer Electronics': 121576, 'Computers': 105769, 'Audio/Video': 99441, 'Furniture': 53656, 'Photo / Cinema Equipment': 25021, 'Construction Materials': 24995, 'Clothing and Accessories': 23554, 'Auto Accessories': 7381, 'Jewelry': 6290, 'Homewares': 5023, 'Medical Supplies': 3843, 'Vehicles': 3370, 'Sport and Leisure': 2981, 'Gardening': 2668, 'Other': 2554, 'Office Appliances': 2333, 'Tourism': 1659, 'Medicine': 1550, 'Direct Sales': 446, 'Fitness': 209, 'Additional Service': 128, 'Education': 107, 'Weapon': 77, 'Insurance': 64, 'House Construction': 1, 'Animals': 1}
NAME_PORTFOLIO (5): {'POS': 691011, 'Cash': 461563, 'XNA': 372230, 'Cards': 144985, 'Cars': 425}
NAME_PRODUCT_TYPE (3): {'XNA': 1063666, 'x-sell': 456287, 'walk-in': 150261}
CHANNEL_TYPE (8): {'Credit and cash offices': 719968, 'Country-wide': 494690, 'Stone': 212083, 'Regional / Local': 108528, 'Contact center': 71297, 'AP+ (Cash loan)': 57046, 'Channel of corporate sales': 6150, 'Car dealer': 452}
NAME_SELLER_INDUSTRY (11): {'XNA': 855720, 'Consumer electronics': 398265, 'Connectivity': 276029, 'Furniture': 57849, 'Construction': 29781, 'Clothing': 23949, 'Industry': 19194, 'Auto technology': 4990, 'Jewelry': 2709, 'MLM partners': 1215, 'Tourism': 513}
NAME_YIELD_GROUP (5): {'XNA': 517215, 'middle': 385532, 'high': 353331, 'low_normal': 322095, 'low_action': 92041}
PRODUCT_COMBINATION (18): {'Cash': 285990, 'POS household with interest': 263622, 'POS mobile with interest': 220670, 'Cash X-Sell: middle': 143883, 'Cash X-Sell: low': 130248, 'Card Street': 112582, 'POS industry with interest': 98833, 'POS household without interest': 82908, 'Card X-Sell': 80582, 'Cash Street: high': 59639, 'Cash X-Sell: high': 59301, 'Cash Street: middle': 34658, 'Cash Street: low': 33834, 'POS mobile without interest': 24082, 'POS other with interest': 23879, 'POS industry without interest': 12602, 'POS others without interest': 2555, None: 346}

CLEAN_PREVIOUS_APPLICATION  TARGET NAME_CONTRACT_TYPE  AMT_ANNUITY  \
SK_ID_CURR SK_ID_PREV
0          752                   1         Cash loans          NaN
           2709                  0     Consumer loans     4274.010
           4201                  0     Consumer loans     4378.860
           4616                  1         Cash loans          NaN
           7852                 -1     Consumer loans          NaN
...                            ...                ...          ...
65535      41383                 1         Cash loans     7559.595
           43291                 0         Cash loans    17389.800
           46102                 0         Cash loans    23496.705
           52566                 0     Consumer loans    11629.170
           60070                 1     Consumer loans     4011.570

CLEAN_PREVIOUS_APPLICATION  AMT_APPLICATION  AMT_CREDIT  AMT_DOWN_PAYMENT  \
SK_ID_CURR SK_ID_PREV
0          752                          0.0         0.0               NaN
           2709                     44050.5     35055.0           13500.0
           4201                     33255.0     32103.0            3600.0
           4616                         0.0         0.0               NaN
           7852                     74565.0     74565.0               0.0
...                                     ...         ...               ...
65535      41383                    67500.0     71955.0               NaN
           43291                    90000.0     90000.0               0.0
           46102                   225000.0    239850.0               NaN
           52566                    97380.0    101578.5            4950.0
           60070                    29205.0     28453.5            2920.5

CLEAN_PREVIOUS_APPLICATION  AMT_GOODS_PRICE WEEKDAY_APPR_PROCESS_START  \
SK_ID_CURR SK_ID_PREV
0          752                          NaN                     MONDAY
           2709                     44050.5                    TUESDAY
           4201                     33255.0                    TUESDAY
           4616                         NaN                   THURSDAY
           7852                     74565.0                  WEDNESDAY
...                                     ...                        ...
65535      41383                    67500.0                     SUNDAY
           43291                    90000.0                     MONDAY
           46102                   225000.0                  WEDNESDAY
           52566                    97380.0                   SATURDAY
           60070                    29205.0                  WEDNESDAY

CLEAN_PREVIOUS_APPLICATION  HOUR_APPR_PROCESS_START  \
SK_ID_CURR SK_ID_PREV
0          752                                   11
           2709                                  12
           4201                                  13
           4616                                  11
           7852                                  20
...                                             ...
65535      41383                                 17
           43291                                  9
           46102                                 13
           52566                                  9
           60070                                 11

CLEAN_PREVIOUS_APPLICATION  FLAG_LAST_APPL_PER_CONTRACT  ...  \
SK_ID_CURR SK_ID_PREV                                    ...
0          752                                        1  ...
           2709                                       1  ...
           4201                                       1  ...
           4616                                       1  ...
           7852                                       1  ...
...                                                 ...  ...
65535      41383                                      1  ...
           43291                                      1  ...
           46102                                      1  ...
           52566                                      1  ...
           60070                                      1  ...

CLEAN_PREVIOUS_APPLICATION  NAME_SELLER_INDUSTRY  CNT_PAYMENT  \
SK_ID_CURR SK_ID_PREV
0          752                               XNA          NaN
           2709                     Connectivity         12.0
           4201                     Connectivity         10.0
           4616                              XNA          NaN
           7852                     Connectivity          NaN
...                                          ...          ...
65535      41383                             XNA         12.0
           43291            Consumer electronics          6.0
           46102                             XNA         12.0
           52566            Consumer electronics         12.0
           60070            Consumer electronics         10.0

CLEAN_PREVIOUS_APPLICATION  NAME_YIELD_GROUP          PRODUCT_COMBINATION  \
SK_ID_CURR SK_ID_PREV
0          752                           XNA                         Cash
           2709                         high     POS mobile with interest
           4201                         high     POS mobile with interest
           4616                          XNA                         Cash
           7852                          XNA     POS mobile with interest
...                                      ...                          ...
65535      41383                      middle          Cash X-Sell: middle
           43291                        high            Cash Street: high
           46102                  low_normal             Cash X-Sell: low
           52566                        high  POS household with interest
           60070                        high  POS household with interest

CLEAN_PREVIOUS_APPLICATION DAYS_FIRST_DRAWING DAYS_FIRST_DUE  \
SK_ID_CURR SK_ID_PREV
0          752                            NaN            NaN
           2709                          -0.0         1004.0
           4201                          -0.0         2026.0
           4616                           NaN            NaN
           7852                           NaN            NaN
...                                       ...            ...
65535      41383                         -0.0         1120.0
           43291                         -0.0         2505.0
           46102                         -0.0          207.0
           52566                         -0.0         1596.0
           60070                         -0.0         2038.0

CLEAN_PREVIOUS_APPLICATION  DAYS_LAST_DUE_1ST_VERSION DAYS_LAST_DUE  \
SK_ID_CURR SK_ID_PREV
0          752                                    NaN           NaN
           2709                                 674.0         674.0
           4201                                1756.0        1756.0
           4616                                   NaN           NaN
           7852                                   NaN           NaN
...                                               ...           ...
65535      41383                                790.0         880.0
           43291                               2355.0        2355.0
           46102                               -123.0          -0.0
           52566                               1266.0        1266.0
           60070                               1768.0        1768.0

CLEAN_PREVIOUS_APPLICATION DAYS_TERMINATION NFLAG_INSURED_ON_APPROVAL
SK_ID_CURR SK_ID_PREV
0          752                          NaN                       NaN
           2709                       665.0                       0.0
           4201                      1485.0                       0.0
           4616                         NaN                       NaN
           7852                         NaN                       NaN
...                                     ...                       ...
65535      41383                      872.0                       0.0
           43291                     2347.0                       0.0
           46102                       -0.0                       1.0
           52566                     1262.0                       0.0
           60070                     1761.0                       0.0

[1670214 rows x 36 columns]

# Tables périphériques agrégées

## **`pos_cash_balance`** étendue groupée par prêt

## **`credit_card_balance`** étendue groupée par prêt

## **`installments_payments`** étendue groupée par prêt

# Adjonction

In [ ]:
import pandas as pd
from home_credit.tables import (
    PreviousApplication,
    POSCashBalance,
    CreditCardBalance,
    InstallmentsPayments
)

from home_credit.groupby import (
    get_bureau_loan_status,
    get_bureau_mean_loan_activity,
    get_bureau_loan_status_by_month,
    get_bureau_loan_activity_by_month,
    get_rle_bureau_loan_feature_variations
)

def get_extended_clean_bureau(
    include_status: bool = True,
    include_activity: bool = True,
    include_status_variation: bool = False,
    include_activity_variation: bool = False
) -> pd.DataFrame:
    pass